tap 'caskroom/cask'
tap 'caskroom/drivers'
tap 'caskroom/eid'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'jhawthorn/fzy'
tap 'shopify/shopify'
cask 'xquartz'
cask 'java'

brew 'coreutils'
brew 'moreutils'
brew 'findutils'

brew 'bash'
brew 'homebrew/versions/bash-completion2'

brew 'vim', args: ['with-override-system-vi']
brew 'gnu-sed', args: ['with-default-names']
brew 'wget', args: ['with-iri']
brew 'curl', args: ['with-libidn', 'with-libmetalink', 'with-libssh2', 'with-nghttp2', 'with-rtmpdump']

brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/screen'
brew 'homebrew/dupes/openssh'

brew 'ack'
brew 'android-platform-tools'
brew 'aria2'
brew 'bfg'
brew 'brightness'
brew 'dark-mode'
brew 'git'
brew 'ffmpeg'
brew 'gdrive'
brew 'gifsicle'
brew 'gnupg2'
brew 'openssl'
brew 'sqlite'
brew 'xz'
brew 'htop-osx'
brew 'id3v2'
brew 'imagemagick@6'
brew 'iperf3'
brew 'lynx'
brew 'minicom'
brew 'mitmproxy'
brew 'mtr'
brew 'netcat'
brew 'ninja'
brew 'nmap'
brew 'p7zip'
brew 'pigz'
brew 'pngcrush'
brew 'postgresql'
brew 'pv'
brew 'redis'
brew 'rename'
brew 'rtmpdump'
brew 'speedtest_cli'
brew 'ssh-copy-id'
brew 'stormssh'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'unar'
brew 'webkit2png'

brew 'nvm'
#brew 'nvm-auto-switch'

brew 'ruby-build'
brew 'rbenv'

brew 'nginx', restart_service: true
brew 'mariadb', restart_service: true

brew 'homebrew/php/php56', restart_service: true
brew 'homebrew/php/php56-mcrypt'
brew 'homebrew/php/php56-xdebug'

brew 'homebrew/php/composer'
brew 'homebrew/php/drush'
brew 'homebrew/php/php-cs-fixer'
brew 'homebrew/php/phpmyadmin'
brew 'homebrew/php/wp-cli'
brew 'homebrew/php/xdebug-osx'

brew 'jhawthorn/fzy/fzy'
brew 'shopify/shopify/themekit'

## Casks

# Utilities
cask 'spectacle'
cask 'flux'
cask 'harvest'
cask '1password'
cask 'istat-menus'
cask 'witch'
#cask 'gpgtools'
cask 'keepingyouawake'
cask 'keybase'
cask 'sequal-pro'
cask 'nagstamon'

# Multimedia?
cask 'adobe-creative-cloud'
cask 'handbrake'
cask 'vlc'
#cask 'airfoil'

# Editors
cask 'atom'
cask 'coda'
cask 'sublime-text'
cask 'textmate'

# Browsers
cask 'firefox'
cask 'google-chrome'

# Other Apps
cask 'bonjour-browser'
cask 'coolterm'
cask 'linein'
cask 'google-drive'
cask 'macpar-deluxe'
cask 'mpeg-streamclip'
cask 'gitup'
cask 'rescuetime'
cask 'nvalt'
cask 'pacifist'
cask 'phonebrowse'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'

# Quicklook Plugins
cask 'betterzipql'
cask 'provisionql'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'quicklookase'
cask 'quicknfo'
cask 'scriptql'
cask 'stringsfile'
cask 'suspicious-package'
cask 'webpquicklook'
